// AUTO-GENERATED by build-data.js
// Do not edit manually

const LEARNING_PLAN = {
  "totalWeeks": 16,
  "phases": [
    {
      "id": "phase1",
      "name": "Java语言基础",
      "weeks": [
        1,
        2,
        3,
        4
      ],
      "items": [
        {
          "week": 1,
          "title": "详细学习计划：环境搭建 + Java基础语法",
          "description": "",
          "objectives": [
            "*：完成上述代码框架的所有TODO",
            "*进阶要求**（可选）：",
            "添加优先级字段（高/中/低）",
            "按优先级排序显示",
            "筛选已完成/未完成"
          ],
          "checkItems": [
            {
              "id": "w1c1",
              "text": "能独立创建Java项目并运行",
              "done": false
            },
            {
              "id": "w1c2",
              "text": "理解8种基本数据类型与包装类区别",
              "done": false
            },
            {
              "id": "w1c3",
              "text": "熟练使用ArrayList的增删改查",
              "done": false
            },
            {
              "id": "w1c4",
              "text": "理解HashMap的基本用法",
              "done": false
            },
            {
              "id": "w1c5",
              "text": "完成待办清单控制台程序",
              "done": false
            },
            {
              "id": "w1c6",
              "text": "完成字符统计程序",
              "done": false
            }
          ],
          "estimatedHours": 20
        },
        {
          "week": 2,
          "title": "详细学习计划：面向对象 + 高级语法",
          "description": "",
          "objectives": [
            "*：创建`Student`类",
            "--"
          ],
          "checkItems": [
            {
              "id": "w2c1",
              "text": "抽象Product类设计合理",
              "done": false
            },
            {
              "id": "w2c2",
              "text": "三种商品类型正确继承",
              "done": false
            },
            {
              "id": "w2c3",
              "text": "使用接口DiscountStrategy实现折扣",
              "done": false
            },
            {
              "id": "w2c4",
              "text": "Stream API完成筛选/排序/搜索",
              "done": false
            },
            {
              "id": "w2c5",
              "text": "异常处理（如库存不足）",
              "done": false
            },
            {
              "id": "w2c6",
              "text": "控制台交互流畅",
              "done": false
            },
            {
              "id": "w2c7",
              "text": "设计合理的类结构（封装、继承、多态）",
              "done": false
            },
            {
              "id": "w2c8",
              "text": "区分和使用抽象类与接口",
              "done": false
            },
            {
              "id": "w2c9",
              "text": "熟练使用Stream API处理集合数据",
              "done": false
            },
            {
              "id": "w2c10",
              "text": "正确处理异常，自定义业务异常",
              "done": false
            }
          ],
          "estimatedHours": 20
        },
        {
          "week": 3,
          "title": "详细学习计划：Maven + 工程化工具",
          "description": "",
          "objectives": [],
          "checkItems": [
            {
              "id": "w3c1",
              "text": "创建标准的Maven项目结构",
              "done": false
            },
            {
              "id": "w3c2",
              "text": "理解pom.xml核心配置",
              "done": false
            },
            {
              "id": "w3c3",
              "text": "熟练使用Maven命令（clean、compile、test、package）",
              "done": false
            },
            {
              "id": "w3c4",
              "text": "为项目编写JUnit 5单元测试",
              "done": false
            },
            {
              "id": "w3c5",
              "text": "使用Lombok简化实体类代码",
              "done": false
            },
            {
              "id": "w3c6",
              "text": "配置和使用SLF4J日志框架",
              "done": false
            },
            {
              "id": "w3c7",
              "text": "理解依赖作用域和传递机制",
              "done": false
            }
          ],
          "estimatedHours": 20
        },
        {
          "week": 4,
          "title": "详细学习计划：Spring Boot入门",
          "description": "",
          "objectives": [],
          "checkItems": [
            {
              "id": "w4c1",
              "text": "统一响应格式（ApiResponse）",
              "done": false
            },
            {
              "id": "w4c2",
              "text": "参数校验（@Valid）",
              "done": false
            },
            {
              "id": "w4c3",
              "text": "全局异常处理",
              "done": false
            },
            {
              "id": "w4c4",
              "text": "请求日志拦截器",
              "done": false
            },
            {
              "id": "w4c5",
              "text": "配置文件（端口、应用名）",
              "done": false
            },
            {
              "id": "w4c6",
              "text": "完整的CRUD接口",
              "done": false
            },
            {
              "id": "w4c7",
              "text": "使用Postman/APIFox测试通过",
              "done": false
            },
            {
              "id": "w4c8",
              "text": "创建Spring Boot项目（通过Initializr或IDEA）",
              "done": false
            },
            {
              "id": "w4c9",
              "text": "理解自动配置原理",
              "done": false
            },
            {
              "id": "w4c10",
              "text": "开发完整的RESTful API（CRUD）",
              "done": false
            }
          ],
          "estimatedHours": 20
        }
      ]
    },
    {
      "id": "phase2",
      "name": "Spring Boot核心",
      "weeks": [
        5,
        6,
        7,
        8,
        9,
        10
      ],
      "items": [
        {
          "week": 5,
          "title": "详细学习计划：数据访问层 - JPA + MySQL",
          "description": "",
          "objectives": [],
          "checkItems": [
            {
              "id": "w5c1",
              "text": "配置Spring Boot连接MySQL",
              "done": false
            },
            {
              "id": "w5c2",
              "text": "使用JPA定义实体和关系",
              "done": false
            },
            {
              "id": "w5c3",
              "text": "使用Repository接口进行CRUD",
              "done": false
            },
            {
              "id": "w5c4",
              "text": "实现一对多、多对多关系",
              "done": false
            },
            {
              "id": "w5c5",
              "text": "使用JPQL和原生SQL查询",
              "done": false
            },
            {
              "id": "w5c6",
              "text": "实现分页和排序",
              "done": false
            },
            {
              "id": "w5c7",
              "text": "了解MyBatis基本用法",
              "done": false
            },
            {
              "id": "w5c8",
              "text": "使用@Transactional管理事务",
              "done": false
            }
          ],
          "estimatedHours": 20
        },
        {
          "week": 6,
          "title": "详细学习计划：认证与安全 - Spring Security + JWT",
          "description": "",
          "objectives": [],
          "checkItems": [
            {
              "id": "w6c1",
              "text": "使用HTTPS（生产环境）",
              "done": false
            },
            {
              "id": "w6c2",
              "text": "密码BCrypt加密（强度10+）",
              "done": false
            },
            {
              "id": "w6c3",
              "text": "JWT密钥足够长且安全存储",
              "done": false
            },
            {
              "id": "w6c4",
              "text": "Token设置合理过期时间",
              "done": false
            },
            {
              "id": "w6c5",
              "text": "敏感接口添加权限控制",
              "done": false
            },
            {
              "id": "w6c6",
              "text": "SQL注入防护（使用JPA/参数化查询）",
              "done": false
            },
            {
              "id": "w6c7",
              "text": "XSS防护（前端转义输出）",
              "done": false
            },
            {
              "id": "w6c8",
              "text": "配置Spring Security安全框架",
              "done": false
            },
            {
              "id": "w6c9",
              "text": "理解过滤器链工作原理",
              "done": false
            },
            {
              "id": "w6c10",
              "text": "使用BCrypt加密密码",
              "done": false
            }
          ],
          "estimatedHours": 20
        },
        {
          "week": 7,
          "title": "详细学习计划：缓存与异步 - Redis + 性能优化",
          "description": "",
          "objectives": [],
          "checkItems": [
            {
              "id": "w7c1",
              "text": "Redis正确配置并连接",
              "done": false
            },
            {
              "id": "w7c2",
              "text": "使用Spring Cache注解缓存数据",
              "done": false
            },
            {
              "id": "w7c3",
              "text": "实现接口限流",
              "done": false
            },
            {
              "id": "w7c4",
              "text": "使用@Async处理异步任务",
              "done": false
            },
            {
              "id": "w7c5",
              "text": "配置定时任务",
              "done": false
            },
            {
              "id": "w7c6",
              "text": "缓存问题解决（穿透/击穿/雪崩）",
              "done": false
            },
            {
              "id": "w7c7",
              "text": "性能对比测试（加缓存前后）",
              "done": false
            },
            {
              "id": "w7c8",
              "text": "配置Redis并Spring Boot连接",
              "done": false
            },
            {
              "id": "w7c9",
              "text": "使用Redis五种数据类型",
              "done": false
            },
            {
              "id": "w7c10",
              "text": "使用Spring Cache注解",
              "done": false
            }
          ],
          "estimatedHours": 20
        },
        {
          "week": 8,
          "title": "详细学习计划：部署与DevOps - 项目上线",
          "description": "",
          "objectives": [],
          "checkItems": [
            {
              "id": "w8c1",
              "text": "访问`http://your-server-ip`看到应用",
              "done": false
            },
            {
              "id": "w8c2",
              "text": "访问`https://your-domain.com`（如配置了域名和SSL）",
              "done": false
            },
            {
              "id": "w8c3",
              "text": "API接口正常响应",
              "done": false
            },
            {
              "id": "w8c4",
              "text": "数据库数据持久化（重启容器数据不丢）",
              "done": false
            },
            {
              "id": "w8c5",
              "text": "日志正常输出",
              "done": false
            },
            {
              "id": "w8c6",
              "text": "编写Dockerfile打包应用",
              "done": false
            },
            {
              "id": "w8c7",
              "text": "使用Docker Compose编排多服务",
              "done": false
            },
            {
              "id": "w8c8",
              "text": "在云服务器部署应用",
              "done": false
            },
            {
              "id": "w8c9",
              "text": "配置Nginx反向代理",
              "done": false
            },
            {
              "id": "w8c10",
              "text": "申请并配置SSL证书（HTTPS）",
              "done": false
            }
          ],
          "estimatedHours": 20
        },
        {
          "week": 9,
          "title": "详细学习计划：认证项目深度实践",
          "description": "",
          "objectives": [],
          "checkItems": [
            {
              "id": "w9c1",
              "text": "RBAC五表结构设计",
              "done": false
            },
            {
              "id": "w9c2",
              "text": "JWT + Refresh Token双Token机制",
              "done": false
            },
            {
              "id": "w9c3",
              "text": "按钮级权限控制（前后端）",
              "done": false
            },
            {
              "id": "w9c4",
              "text": "数据权限（部门范围）",
              "done": false
            },
            {
              "id": "w9c5",
              "text": "操作审计日志",
              "done": false
            },
            {
              "id": "w9c6",
              "text": "权限缓存（Redis）",
              "done": false
            },
            {
              "id": "w9c7",
              "text": "角色变更实时生效",
              "done": false
            },
            {
              "id": "w9c8",
              "text": "设计RBAC五表权限模型",
              "done": false
            },
            {
              "id": "w9c9",
              "text": "实现JWT双Token刷新机制",
              "done": false
            },
            {
              "id": "w9c10",
              "text": "按钮级权限控制",
              "done": false
            }
          ],
          "estimatedHours": 40
        },
        {
          "week": 10,
          "title": "Week 10",
          "description": "",
          "objectives": [],
          "checkItems": [
            {
              "id": "w10c1",
              "text": "RBAC五表结构设计",
              "done": false
            },
            {
              "id": "w10c2",
              "text": "JWT + Refresh Token双Token机制",
              "done": false
            },
            {
              "id": "w10c3",
              "text": "按钮级权限控制（前后端）",
              "done": false
            },
            {
              "id": "w10c4",
              "text": "数据权限（部门范围）",
              "done": false
            },
            {
              "id": "w10c5",
              "text": "操作审计日志",
              "done": false
            },
            {
              "id": "w10c6",
              "text": "权限缓存（Redis）",
              "done": false
            },
            {
              "id": "w10c7",
              "text": "角色变更实时生效",
              "done": false
            },
            {
              "id": "w10c8",
              "text": "设计RBAC五表权限模型",
              "done": false
            },
            {
              "id": "w10c9",
              "text": "实现JWT双Token刷新机制",
              "done": false
            },
            {
              "id": "w10c10",
              "text": "按钮级权限控制",
              "done": false
            }
          ],
          "estimatedHours": 40
        }
      ]
    },
    {
      "id": "phase3",
      "name": "进阶与全栈实战",
      "weeks": [
        11,
        12,
        13,
        14,
        15,
        16
      ],
      "items": [
        {
          "week": 11,
          "title": "详细学习计划：性能优化进阶",
          "description": "",
          "objectives": [],
          "checkItems": [
            {
              "id": "w11c1",
              "text": "理解JVM内存结构和GC原理",
              "done": false
            },
            {
              "id": "w11c2",
              "text": "配置JVM参数进行基础调优",
              "done": false
            },
            {
              "id": "w11c3",
              "text": "使用EXPLAIN分析SQL性能",
              "done": false
            },
            {
              "id": "w11c4",
              "text": "解决N+1查询问题",
              "done": false
            },
            {
              "id": "w11c5",
              "text": "实施接口优化（异步、缓存、限流）",
              "done": false
            },
            {
              "id": "w11c6",
              "text": "使用JMeter进行压力测试",
              "done": false
            }
          ],
          "estimatedHours": 40
        },
        {
          "week": 12,
          "title": "Week 12",
          "description": "",
          "objectives": [],
          "checkItems": [
            {
              "id": "w12c1",
              "text": "理解JVM内存结构和GC原理",
              "done": false
            },
            {
              "id": "w12c2",
              "text": "配置JVM参数进行基础调优",
              "done": false
            },
            {
              "id": "w12c3",
              "text": "使用EXPLAIN分析SQL性能",
              "done": false
            },
            {
              "id": "w12c4",
              "text": "解决N+1查询问题",
              "done": false
            },
            {
              "id": "w12c5",
              "text": "实施接口优化（异步、缓存、限流）",
              "done": false
            },
            {
              "id": "w12c6",
              "text": "使用JMeter进行压力测试",
              "done": false
            }
          ],
          "estimatedHours": 40
        },
        {
          "week": 13,
          "title": "详细学习计划：消息队列 - RabbitMQ",
          "description": "",
          "objectives": [],
          "checkItems": [
            {
              "id": "w13c1",
              "text": "理解AMQP核心概念",
              "done": false
            },
            {
              "id": "w13c2",
              "text": "掌握三种交换机类型使用",
              "done": false
            },
            {
              "id": "w13c3",
              "text": "实现延迟消息（超时取消）",
              "done": false
            },
            {
              "id": "w13c4",
              "text": "实现可靠消息投递",
              "done": false
            },
            {
              "id": "w13c5",
              "text": "使用消息队列实现削峰",
              "done": false
            }
          ],
          "estimatedHours": 20
        },
        {
          "week": 14,
          "title": "详细学习计划：高级主题与工程实践",
          "description": "",
          "objectives": [],
          "checkItems": [
            {
              "id": "w14c1",
              "text": "实现文件上传与云存储",
              "done": false
            },
            {
              "id": "w14c2",
              "text": "集成Elasticsearch实现全文搜索",
              "done": false
            },
            {
              "id": "w14c3",
              "text": "理解分布式ID和分布式锁",
              "done": false
            },
            {
              "id": "w14c4",
              "text": "设计幂等接口",
              "done": false
            }
          ],
          "estimatedHours": 40
        },
        {
          "week": 15,
          "title": "Week 15",
          "description": "",
          "objectives": [],
          "checkItems": [
            {
              "id": "w15c1",
              "text": "实现文件上传与云存储",
              "done": false
            },
            {
              "id": "w15c2",
              "text": "集成Elasticsearch实现全文搜索",
              "done": false
            },
            {
              "id": "w15c3",
              "text": "理解分布式ID和分布式锁",
              "done": false
            },
            {
              "id": "w15c4",
              "text": "设计幂等接口",
              "done": false
            }
          ],
          "estimatedHours": 40
        },
        {
          "week": 16,
          "title": "详细学习计划：综合项目实战",
          "description": "",
          "objectives": [],
          "checkItems": [
            {
              "id": "w16c1",
              "text": "用户注册/登录/登出",
              "done": false
            },
            {
              "id": "w16c2",
              "text": "JWT认证与刷新Token",
              "done": false
            },
            {
              "id": "w16c3",
              "text": "个人资料管理",
              "done": false
            },
            {
              "id": "w16c4",
              "text": "项目CRUD（创建者权限）",
              "done": false
            },
            {
              "id": "w16c5",
              "text": "项目成员管理（邀请/移除）",
              "done": false
            },
            {
              "id": "w16c6",
              "text": "任务CRUD（项目内）",
              "done": false
            },
            {
              "id": "w16c7",
              "text": "任务状态流转",
              "done": false
            },
            {
              "id": "w16c8",
              "text": "任务分配与优先级",
              "done": false
            },
            {
              "id": "w16c9",
              "text": "任务评论",
              "done": false
            },
            {
              "id": "w16c10",
              "text": "文件附件上传（本地或OSS）",
              "done": false
            }
          ],
          "estimatedHours": 30
        }
      ]
    }
  ]
};

// Export for module environments
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { LEARNING_PLAN };
}
