// AUTO-GENERATED by build-data.js
// Do not edit manually
// Generated at: 2026-04-15T01:22:31.558Z

const LEARNING_PLAN = {
  "totalWeeks": 16,
  "phases": [
    {
      "id": "phase1",
      "name": "Java语言基础",
      "weeks": [
        1,
        2,
        3,
        4
      ],
      "items": [
        {
          "week": 1,
          "title": "详细学习计划：环境搭建 + Java基础语法",
          "description": "搭建Java开发环境，掌握基础语法，能独立编写控制台程序",
          "objectives": [
            "搭建Java开发环境，掌握基础语法，能独立编写控制台程序",
            "两个可运行的控制台程序（计算器 + 待办清单）"
          ],
          "checkItems": [
            {
              "id": "w1c1",
              "text": "能独立创建Java项目并运行",
              "done": false
            },
            {
              "id": "w1c2",
              "text": "理解8种基本数据类型与包装类区别",
              "done": false
            },
            {
              "id": "w1c3",
              "text": "熟练使用ArrayList的增删改查",
              "done": false
            },
            {
              "id": "w1c4",
              "text": "理解HashMap的基本用法",
              "done": false
            },
            {
              "id": "w1c5",
              "text": "完成待办清单控制台程序",
              "done": false
            },
            {
              "id": "w1c6",
              "text": "完成字符统计程序",
              "done": false
            }
          ],
          "estimatedHours": 15
        },
        {
          "week": 2,
          "title": "详细学习计划：面向对象 + 高级语法",
          "description": "掌握Java面向对象编程，理解类设计，熟练使用Stream API",
          "objectives": [
            "掌握Java面向对象编程，理解类设计，熟练使用Stream API",
            "电商商品类体系设计 + 数据处理器（Stream练习）"
          ],
          "checkItems": [
            {
              "id": "w2c1",
              "text": "抽象Product类设计合理",
              "done": false
            },
            {
              "id": "w2c2",
              "text": "三种商品类型正确继承",
              "done": false
            },
            {
              "id": "w2c3",
              "text": "使用接口DiscountStrategy实现折扣",
              "done": false
            },
            {
              "id": "w2c4",
              "text": "Stream API完成筛选/排序/搜索",
              "done": false
            },
            {
              "id": "w2c5",
              "text": "异常处理（如库存不足）",
              "done": false
            },
            {
              "id": "w2c6",
              "text": "控制台交互流畅",
              "done": false
            },
            {
              "id": "w2c7",
              "text": "设计合理的类结构（封装、继承、多态）",
              "done": false
            },
            {
              "id": "w2c8",
              "text": "区分和使用抽象类与接口",
              "done": false
            },
            {
              "id": "w2c9",
              "text": "熟练使用Stream API处理集合数据",
              "done": false
            },
            {
              "id": "w2c10",
              "text": "正确处理异常，自定义业务异常",
              "done": false
            },
            {
              "id": "w2c11",
              "text": "独立完成一个小型OOP项目",
              "done": false
            }
          ],
          "estimatedHours": 15
        },
        {
          "week": 3,
          "title": "详细学习计划：Maven + 工程化工具",
          "description": "掌握Java项目构建，能使用工程化工具提高开发效率",
          "objectives": [
            "掌握Java项目构建，能使用工程化工具提高开发效率",
            "规范的Maven项目 + 完整的单元测试覆盖 + 使用Lombok重构代码"
          ],
          "checkItems": [
            {
              "id": "w3c1",
              "text": "创建标准的Maven项目结构",
              "done": false
            },
            {
              "id": "w3c2",
              "text": "理解pom.xml核心配置",
              "done": false
            },
            {
              "id": "w3c3",
              "text": "熟练使用Maven命令（clean、compile、test、package）",
              "done": false
            },
            {
              "id": "w3c4",
              "text": "为项目编写JUnit 5单元测试",
              "done": false
            },
            {
              "id": "w3c5",
              "text": "使用Lombok简化实体类代码",
              "done": false
            },
            {
              "id": "w3c6",
              "text": "配置和使用SLF4J日志框架",
              "done": false
            },
            {
              "id": "w3c7",
              "text": "理解依赖作用域和传递机制",
              "done": false
            }
          ],
          "estimatedHours": 15
        },
        {
          "week": 4,
          "title": "详细学习计划：Spring Boot入门",
          "description": "掌握Spring Boot基础，能搭建Web项目并开发REST API",
          "objectives": [
            "掌握Spring Boot基础，能搭建Web项目并开发REST API",
            "第一个Spring Boot项目 + 完整的CRUD REST API"
          ],
          "checkItems": [
            {
              "id": "w4c1",
              "text": "统一响应格式（ApiResponse）",
              "done": false
            },
            {
              "id": "w4c2",
              "text": "参数校验（@Valid）",
              "done": false
            },
            {
              "id": "w4c3",
              "text": "全局异常处理",
              "done": false
            },
            {
              "id": "w4c4",
              "text": "请求日志拦截器",
              "done": false
            },
            {
              "id": "w4c5",
              "text": "配置文件（端口、应用名）",
              "done": false
            },
            {
              "id": "w4c6",
              "text": "完整的CRUD接口",
              "done": false
            },
            {
              "id": "w4c7",
              "text": "使用Postman/APIFox测试通过",
              "done": false
            },
            {
              "id": "w4c8",
              "text": "创建Spring Boot项目（通过Initializr或IDEA）",
              "done": false
            },
            {
              "id": "w4c9",
              "text": "理解自动配置原理",
              "done": false
            },
            {
              "id": "w4c10",
              "text": "开发完整的RESTful API（CRUD）",
              "done": false
            },
            {
              "id": "w4c11",
              "text": "统一响应格式和异常处理",
              "done": false
            },
            {
              "id": "w4c12",
              "text": "使用配置文件管理配置",
              "done": false
            },
            {
              "id": "w4c13",
              "text": "添加拦截器记录请求日志",
              "done": false
            },
            {
              "id": "w4c14",
              "text": "使用Postman测试API",
              "done": false
            }
          ],
          "estimatedHours": 15
        }
      ]
    },
    {
      "id": "phase2",
      "name": "Spring Boot核心",
      "weeks": [
        5,
        6,
        7,
        8,
        9,
        10
      ],
      "items": [
        {
          "week": 5,
          "title": "详细学习计划：数据访问层 - JPA + MySQL",
          "description": "掌握数据库连接与持久化，能使用JPA和MyBatis操作数据",
          "objectives": [
            "掌握数据库连接与持久化，能使用JPA和MyBatis操作数据",
            "连接MySQL的完整CRUD项目 + 理解ORM思想"
          ],
          "checkItems": [
            {
              "id": "w5c1",
              "text": "配置Spring Boot连接MySQL",
              "done": false
            },
            {
              "id": "w5c2",
              "text": "使用JPA定义实体和关系",
              "done": false
            },
            {
              "id": "w5c3",
              "text": "使用Repository接口进行CRUD",
              "done": false
            },
            {
              "id": "w5c4",
              "text": "实现一对多、多对多关系",
              "done": false
            },
            {
              "id": "w5c5",
              "text": "使用JPQL和原生SQL查询",
              "done": false
            },
            {
              "id": "w5c6",
              "text": "实现分页和排序",
              "done": false
            },
            {
              "id": "w5c7",
              "text": "了解MyBatis基本用法",
              "done": false
            },
            {
              "id": "w5c8",
              "text": "使用@Transactional管理事务",
              "done": false
            }
          ],
          "estimatedHours": 15
        },
        {
          "week": 6,
          "title": "详细学习计划：认证与安全 - Spring Security + JWT",
          "description": "掌握Spring Security框架，实现JWT认证，保护API安全",
          "objectives": [
            "掌握Spring Security框架，实现JWT认证，保护API安全",
            "带JWT认证的完整用户系统 + 权限控制"
          ],
          "checkItems": [
            {
              "id": "w6c1",
              "text": "使用HTTPS（生产环境）",
              "done": false
            },
            {
              "id": "w6c2",
              "text": "密码BCrypt加密（强度10+）",
              "done": false
            },
            {
              "id": "w6c3",
              "text": "JWT密钥足够长且安全存储",
              "done": false
            },
            {
              "id": "w6c4",
              "text": "Token设置合理过期时间",
              "done": false
            },
            {
              "id": "w6c5",
              "text": "敏感接口添加权限控制",
              "done": false
            },
            {
              "id": "w6c6",
              "text": "SQL注入防护（使用JPA/参数化查询）",
              "done": false
            },
            {
              "id": "w6c7",
              "text": "XSS防护（前端转义输出）",
              "done": false
            },
            {
              "id": "w6c8",
              "text": "配置Spring Security安全框架",
              "done": false
            },
            {
              "id": "w6c9",
              "text": "理解过滤器链工作原理",
              "done": false
            },
            {
              "id": "w6c10",
              "text": "使用BCrypt加密密码",
              "done": false
            },
            {
              "id": "w6c11",
              "text": "实现JWT生成与验证",
              "done": false
            },
            {
              "id": "w6c12",
              "text": "完成用户注册/登录功能",
              "done": false
            },
            {
              "id": "w6c13",
              "text": "实现JWT认证过滤器",
              "done": false
            },
            {
              "id": "w6c14",
              "text": "使用方法注解控制权限",
              "done": false
            },
            {
              "id": "w6c15",
              "text": "前后端JWT对接",
              "done": false
            }
          ],
          "estimatedHours": 15
        },
        {
          "week": 7,
          "title": "详细学习计划：缓存与异步 - Redis + 性能优化",
          "description": "掌握Redis缓存，理解异步处理，提升系统性能",
          "objectives": [
            "掌握Redis缓存，理解异步处理，提升系统性能",
            "带缓存的博客系统 + 异步任务处理"
          ],
          "checkItems": [
            {
              "id": "w7c1",
              "text": "Redis正确配置并连接",
              "done": false
            },
            {
              "id": "w7c2",
              "text": "使用Spring Cache注解缓存数据",
              "done": false
            },
            {
              "id": "w7c3",
              "text": "实现接口限流",
              "done": false
            },
            {
              "id": "w7c4",
              "text": "使用@Async处理异步任务",
              "done": false
            },
            {
              "id": "w7c5",
              "text": "配置定时任务",
              "done": false
            },
            {
              "id": "w7c6",
              "text": "缓存问题解决（穿透/击穿/雪崩）",
              "done": false
            },
            {
              "id": "w7c7",
              "text": "性能对比测试（加缓存前后）",
              "done": false
            },
            {
              "id": "w7c8",
              "text": "配置Redis并Spring Boot连接",
              "done": false
            },
            {
              "id": "w7c9",
              "text": "使用Redis五种数据类型",
              "done": false
            },
            {
              "id": "w7c10",
              "text": "使用Spring Cache注解",
              "done": false
            },
            {
              "id": "w7c11",
              "text": "实现接口限流",
              "done": false
            },
            {
              "id": "w7c12",
              "text": "使用@Async处理异步任务",
              "done": false
            },
            {
              "id": "w7c13",
              "text": "配置定时任务",
              "done": false
            },
            {
              "id": "w7c14",
              "text": "处理缓存三穿问题",
              "done": false
            }
          ],
          "estimatedHours": 15
        },
        {
          "week": 8,
          "title": "详细学习计划：部署与DevOps - 项目上线",
          "description": "掌握容器化部署，能将Spring Boot应用部署到云服务器",
          "objectives": [
            "掌握容器化部署，能将Spring Boot应用部署到云服务器",
            "线上可访问的完整应用 + 自动化部署流程"
          ],
          "checkItems": [
            {
              "id": "w8c1",
              "text": "购买/准备云服务器",
              "done": false
            },
            {
              "id": "w8c2",
              "text": "域名解析到服务器（可选）",
              "done": false
            },
            {
              "id": "w8c3",
              "text": "准备项目代码",
              "done": false
            },
            {
              "id": "w8c4",
              "text": "编写Dockerfile",
              "done": false
            },
            {
              "id": "w8c5",
              "text": "编写docker-compose.yml",
              "done": false
            },
            {
              "id": "w8c6",
              "text": "本地测试：`docker compose up`",
              "done": false
            },
            {
              "id": "w8c7",
              "text": "上传代码到服务器",
              "done": false
            },
            {
              "id": "w8c8",
              "text": "启动服务：`docker compose up -d`",
              "done": false
            },
            {
              "id": "w8c9",
              "text": "配置Nginx反向代理",
              "done": false
            },
            {
              "id": "w8c10",
              "text": "测试访问",
              "done": false
            },
            {
              "id": "w8c11",
              "text": "申请Let's Encrypt证书",
              "done": false
            },
            {
              "id": "w8c12",
              "text": "配置Nginx SSL",
              "done": false
            },
            {
              "id": "w8c13",
              "text": "测试HTTPS访问",
              "done": false
            },
            {
              "id": "w8c14",
              "text": "访问`http://your-server-ip`看到应用",
              "done": false
            },
            {
              "id": "w8c15",
              "text": "访问`https://your-domain.com`（如配置了域名和SSL）",
              "done": false
            },
            {
              "id": "w8c16",
              "text": "API接口正常响应",
              "done": false
            },
            {
              "id": "w8c17",
              "text": "数据库数据持久化（重启容器数据不丢）",
              "done": false
            },
            {
              "id": "w8c18",
              "text": "日志正常输出",
              "done": false
            },
            {
              "id": "w8c19",
              "text": "编写Dockerfile打包应用",
              "done": false
            },
            {
              "id": "w8c20",
              "text": "使用Docker Compose编排多服务",
              "done": false
            },
            {
              "id": "w8c21",
              "text": "在云服务器部署应用",
              "done": false
            },
            {
              "id": "w8c22",
              "text": "配置Nginx反向代理",
              "done": false
            },
            {
              "id": "w8c23",
              "text": "申请并配置SSL证书（HTTPS）",
              "done": false
            },
            {
              "id": "w8c24",
              "text": "配置GitHub Actions自动部署",
              "done": false
            },
            {
              "id": "w8c25",
              "text": "基础故障排查",
              "done": false
            }
          ],
          "estimatedHours": 15
        },
        {
          "week": 9,
          "title": "详细学习计划：认证项目深度实践",
          "description": "构建完整的权限管理系统，深入理解RBAC和OAuth2",
          "objectives": [
            "构建完整的权限管理系统，深入理解RBAC和OAuth2",
            "带角色权限的企业级权限管理系统"
          ],
          "checkItems": [
            {
              "id": "w9c1",
              "text": "RBAC五表结构设计",
              "done": false
            },
            {
              "id": "w9c2",
              "text": "JWT + Refresh Token双Token机制",
              "done": false
            },
            {
              "id": "w9c3",
              "text": "按钮级权限控制（前后端）",
              "done": false
            },
            {
              "id": "w9c4",
              "text": "数据权限（部门范围）",
              "done": false
            },
            {
              "id": "w9c5",
              "text": "操作审计日志",
              "done": false
            },
            {
              "id": "w9c6",
              "text": "权限缓存（Redis）",
              "done": false
            },
            {
              "id": "w9c7",
              "text": "角色变更实时生效",
              "done": false
            },
            {
              "id": "w9c8",
              "text": "设计RBAC五表权限模型",
              "done": false
            },
            {
              "id": "w9c9",
              "text": "实现JWT双Token刷新机制",
              "done": false
            },
            {
              "id": "w9c10",
              "text": "按钮级权限控制",
              "done": false
            },
            {
              "id": "w9c11",
              "text": "数据权限范围控制",
              "done": false
            },
            {
              "id": "w9c12",
              "text": "操作审计日志",
              "done": false
            },
            {
              "id": "w9c13",
              "text": "权限缓存与实时刷新",
              "done": false
            }
          ],
          "estimatedHours": 30
        },
        {
          "week": 10,
          "title": "详细学习计划：认证项目深度实践",
          "description": "构建完整的权限管理系统，深入理解RBAC和OAuth2",
          "objectives": [
            "构建完整的权限管理系统，深入理解RBAC和OAuth2",
            "带角色权限的企业级权限管理系统"
          ],
          "checkItems": [
            {
              "id": "w10c1",
              "text": "RBAC五表结构设计",
              "done": false
            },
            {
              "id": "w10c2",
              "text": "JWT + Refresh Token双Token机制",
              "done": false
            },
            {
              "id": "w10c3",
              "text": "按钮级权限控制（前后端）",
              "done": false
            },
            {
              "id": "w10c4",
              "text": "数据权限（部门范围）",
              "done": false
            },
            {
              "id": "w10c5",
              "text": "操作审计日志",
              "done": false
            },
            {
              "id": "w10c6",
              "text": "权限缓存（Redis）",
              "done": false
            },
            {
              "id": "w10c7",
              "text": "角色变更实时生效",
              "done": false
            },
            {
              "id": "w10c8",
              "text": "设计RBAC五表权限模型",
              "done": false
            },
            {
              "id": "w10c9",
              "text": "实现JWT双Token刷新机制",
              "done": false
            },
            {
              "id": "w10c10",
              "text": "按钮级权限控制",
              "done": false
            },
            {
              "id": "w10c11",
              "text": "数据权限范围控制",
              "done": false
            },
            {
              "id": "w10c12",
              "text": "操作审计日志",
              "done": false
            },
            {
              "id": "w10c13",
              "text": "权限缓存与实时刷新",
              "done": false
            }
          ],
          "estimatedHours": 30
        }
      ]
    },
    {
      "id": "phase3",
      "name": "进阶与全栈实战",
      "weeks": [
        11,
        12,
        13,
        14,
        15,
        16
      ],
      "items": [
        {
          "week": 11,
          "title": "详细学习计划：性能优化进阶",
          "description": "掌握JVM调优、SQL优化、接口性能优化",
          "objectives": [
            "掌握JVM调优、SQL优化、接口性能优化",
            "能独立进行性能诊断和优化"
          ],
          "checkItems": [
            {
              "id": "w11c1",
              "text": "理解JVM内存结构和GC原理",
              "done": false
            },
            {
              "id": "w11c2",
              "text": "配置JVM参数进行基础调优",
              "done": false
            },
            {
              "id": "w11c3",
              "text": "使用EXPLAIN分析SQL性能",
              "done": false
            },
            {
              "id": "w11c4",
              "text": "解决N+1查询问题",
              "done": false
            },
            {
              "id": "w11c5",
              "text": "实施接口优化（异步、缓存、限流）",
              "done": false
            },
            {
              "id": "w11c6",
              "text": "使用JMeter进行压力测试",
              "done": false
            }
          ],
          "estimatedHours": 30
        },
        {
          "week": 12,
          "title": "详细学习计划：性能优化进阶",
          "description": "掌握JVM调优、SQL优化、接口性能优化",
          "objectives": [
            "掌握JVM调优、SQL优化、接口性能优化",
            "能独立进行性能诊断和优化"
          ],
          "checkItems": [
            {
              "id": "w12c1",
              "text": "理解JVM内存结构和GC原理",
              "done": false
            },
            {
              "id": "w12c2",
              "text": "配置JVM参数进行基础调优",
              "done": false
            },
            {
              "id": "w12c3",
              "text": "使用EXPLAIN分析SQL性能",
              "done": false
            },
            {
              "id": "w12c4",
              "text": "解决N+1查询问题",
              "done": false
            },
            {
              "id": "w12c5",
              "text": "实施接口优化（异步、缓存、限流）",
              "done": false
            },
            {
              "id": "w12c6",
              "text": "使用JMeter进行压力测试",
              "done": false
            }
          ],
          "estimatedHours": 30
        },
        {
          "week": 13,
          "title": "详细学习计划：消息队列 - RabbitMQ",
          "description": "掌握消息队列核心概念，能使用RabbitMQ实现异步通信",
          "objectives": [
            "掌握消息队列核心概念，能使用RabbitMQ实现异步通信",
            "可靠的消息投递系统"
          ],
          "checkItems": [
            {
              "id": "w13c1",
              "text": "理解AMQP核心概念",
              "done": false
            },
            {
              "id": "w13c2",
              "text": "掌握三种交换机类型使用",
              "done": false
            },
            {
              "id": "w13c3",
              "text": "实现延迟消息（超时取消）",
              "done": false
            },
            {
              "id": "w13c4",
              "text": "实现可靠消息投递",
              "done": false
            },
            {
              "id": "w13c5",
              "text": "使用消息队列实现削峰",
              "done": false
            }
          ],
          "estimatedHours": 15
        },
        {
          "week": 14,
          "title": "详细学习计划：高级主题与工程实践",
          "description": "掌握高级开发技能，准备生产环境",
          "objectives": [
            "掌握高级开发技能，准备生产环境",
            "企业级工程能力"
          ],
          "checkItems": [
            {
              "id": "w14c1",
              "text": "实现文件上传与云存储",
              "done": false
            },
            {
              "id": "w14c2",
              "text": "集成Elasticsearch实现全文搜索",
              "done": false
            },
            {
              "id": "w14c3",
              "text": "理解分布式ID和分布式锁",
              "done": false
            },
            {
              "id": "w14c4",
              "text": "设计幂等接口",
              "done": false
            }
          ],
          "estimatedHours": 30
        },
        {
          "week": 15,
          "title": "详细学习计划：高级主题与工程实践",
          "description": "掌握高级开发技能，准备生产环境",
          "objectives": [
            "掌握高级开发技能，准备生产环境",
            "企业级工程能力"
          ],
          "checkItems": [
            {
              "id": "w15c1",
              "text": "实现文件上传与云存储",
              "done": false
            },
            {
              "id": "w15c2",
              "text": "集成Elasticsearch实现全文搜索",
              "done": false
            },
            {
              "id": "w15c3",
              "text": "理解分布式ID和分布式锁",
              "done": false
            },
            {
              "id": "w15c4",
              "text": "设计幂等接口",
              "done": false
            }
          ],
          "estimatedHours": 30
        },
        {
          "week": 16,
          "title": "详细学习计划：综合项目实战",
          "description": "整合所学知识，完成企业级全栈项目",
          "objectives": [
            "整合所学知识，完成企业级全栈项目",
            "可写入简历的生产级项目"
          ],
          "checkItems": [
            {
              "id": "w16c1",
              "text": "用户注册/登录/登出",
              "done": false
            },
            {
              "id": "w16c2",
              "text": "JWT认证与刷新Token",
              "done": false
            },
            {
              "id": "w16c3",
              "text": "个人资料管理",
              "done": false
            },
            {
              "id": "w16c4",
              "text": "项目CRUD（创建者权限）",
              "done": false
            },
            {
              "id": "w16c5",
              "text": "项目成员管理（邀请/移除）",
              "done": false
            },
            {
              "id": "w16c6",
              "text": "任务CRUD（项目内）",
              "done": false
            },
            {
              "id": "w16c7",
              "text": "任务状态流转",
              "done": false
            },
            {
              "id": "w16c8",
              "text": "任务分配与优先级",
              "done": false
            },
            {
              "id": "w16c9",
              "text": "任务评论",
              "done": false
            },
            {
              "id": "w16c10",
              "text": "文件附件上传（本地或OSS）",
              "done": false
            },
            {
              "id": "w16c11",
              "text": "通知系统（任务分配提醒、评论提醒）",
              "done": false
            },
            {
              "id": "w16c12",
              "text": "操作日志（任务变更记录）",
              "done": false
            },
            {
              "id": "w16c13",
              "text": "看板视图API（按状态分组）",
              "done": false
            },
            {
              "id": "w16c14",
              "text": "全局搜索（任务/项目模糊搜索）",
              "done": false
            },
            {
              "id": "w16c15",
              "text": "Redis缓存（热门项目、用户会话）",
              "done": false
            },
            {
              "id": "w16c16",
              "text": "接口限流防刷",
              "done": false
            },
            {
              "id": "w16c17",
              "text": "统计报表（个人/项目维度）",
              "done": false
            },
            {
              "id": "w16c18",
              "text": "WebSocket实时通知",
              "done": false
            },
            {
              "id": "w16c19",
              "text": "Docker容器化部署",
              "done": false
            },
            {
              "id": "w16c20",
              "text": "完成项目基础功能",
              "done": false
            },
            {
              "id": "w16c21",
              "text": "实现认证与权限",
              "done": false
            },
            {
              "id": "w16c22",
              "text": "编写API文档",
              "done": false
            },
            {
              "id": "w16c23",
              "text": "部署到服务器",
              "done": false
            },
            {
              "id": "w16c24",
              "text": "准备项目演示",
              "done": false
            }
          ],
          "estimatedHours": 20
        }
      ]
    }
  ]
};

// Export for module environments
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { LEARNING_PLAN };
}
