const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.resolve(__dirname, '../..');
const OUTPUT_FILE = path.join(ROOT_DIR, 'tracker/js/data.js');

const PHASES = [
    { id: 'phase1', name: 'Java语言基础', weeks: [1, 2, 3, 4] },
    { id: 'phase2', name: 'Spring Boot核心', weeks: [5, 6, 7, 8, 9, 10] },
    { id: 'phase3', name: '进阶与全栈实战', weeks: [11, 12, 13, 14, 15, 16] }
];

function findWeekFile(weekNum) {
    // Try different filename patterns
    const patterns = [
        `week${weekNum}-detailed-plan.md`,
        `week${weekNum}-${weekNum + 1}-detailed-plan.md`,  // e.g., week9-10
        `week${weekNum - 1}-${weekNum}-detailed-plan.md`,  // e.g., week11 in 11-12
    ];

    for (const pattern of patterns) {
        const filePath = path.join(ROOT_DIR, pattern);
        if (fs.existsSync(filePath)) {
            return filePath;
        }
    }
    return null;
}

function parseWeekFile(weekNum) {
    const filePath = findWeekFile(weekNum);

    if (!filePath) {
        console.warn(`File not found for week ${weekNum}`);
        return null;
    }

    const content = fs.readFileSync(filePath, 'utf-8');

    // Extract title - try multiple patterns
    let title = '';
    const titlePatterns = [
        new RegExp(`# Week ${weekNum}[\\s:：]+(.+)`),
        new RegExp(`## Week ${weekNum}[\\s:：]+(.+)`),
        new RegExp(`# Week ${weekNum}-${weekNum+1}[\\s:：]+(.+)`),
        new RegExp(`## Week ${weekNum}-${weekNum+1}[\\s:：]+(.+)`),
    ];

    for (const pattern of titlePatterns) {
        const match = content.match(pattern);
        if (match) {
            title = match[1].trim();
            break;
        }
    }

    // Extract objectives from "目标" or "预期产出" or "学习目标" sections
    const objectives = [];
    const objectivePatterns = [
        /##[^#]*(?:目标|预期产出|学习目标)([\s\S]*?)(?=##|$)/i,
        /###[^#]*(?:目标|预期产出|学习目标)([\s\S]*?)(?=###|##|$)/i,
    ];

    for (const pattern of objectivePatterns) {
        const objectiveSection = content.match(pattern);
        if (objectiveSection) {
            const objLines = objectiveSection[1].split('\n');
            for (const line of objLines) {
                const match = line.match(/^[-*]\s*(.+)$/);
                if (match && match[1].trim()) {
                    objectives.push(match[1].trim());
                }
            }
            if (objectives.length > 0) break;
        }
    }

    // Extract check items from checkboxes in the whole file
    const checkItems = [];
    const checkboxRegex = /^[-*]\s*\[([ x])\]\s*(.+)$/gm;
    let match;
    while ((match = checkboxRegex.exec(content)) !== null) {
        checkItems.push({
            id: `w${weekNum}c${checkItems.length + 1}`,
            text: match[2].trim(),
            done: match[1].toLowerCase() === 'x'
        });
    }

    // Extract estimated hours from time allocation tables or text
    let estimatedHours = 0;
    const hourPatterns = [
        /(\d+)\s*小时/,
        /投入时间[：:]\s*~?(\d+)/i,
        /预计学习时间[：:]\s*~?(\d+)/i,
        /本周时间投入[：:]\s*~?(\d+)/i,
    ];

    for (const pattern of hourPatterns) {
        const hourMatch = content.match(pattern);
        if (hourMatch) {
            estimatedHours = parseInt(hourMatch[1], 10);
            break;
        }
    }

    return {
        week: weekNum,
        title: title || `Week ${weekNum}`,
        description: '',
        objectives: objectives.slice(0, 5),
        checkItems: checkItems.slice(0, 10),
        estimatedHours: estimatedHours || 18
    };
}

function generateData() {
    const plan = {
        totalWeeks: 16,
        phases: PHASES.map(phase => ({
            ...phase,
            items: phase.weeks.map(w => parseWeekFile(w)).filter(Boolean)
        }))
    };

    const output = `// AUTO-GENERATED by build-data.js
// Do not edit manually

const LEARNING_PLAN = ${JSON.stringify(plan, null, 2)};

// Export for module environments
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { LEARNING_PLAN };
}
`;

    fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
    fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');

    console.log(`Generated ${OUTPUT_FILE}`);
    console.log(`Total weeks: ${plan.phases.reduce((sum, p) => sum + p.items.length, 0)}`);
}

generateData();
